apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vortex.fullname" . }}-config
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
data:
  VORTEX_LOG_LEVEL: {{ .Values.logging.level | quote }}
  VORTEX_LOG_FORMAT: {{ .Values.logging.format | quote }}
  VORTEX_HTTP_PORT: {{ .Values.service.httpPort | quote }}
  VORTEX_GRPC_PORT: {{ .Values.service.grpcPort | quote }}
