apiVersion: v1
kind: Service
metadata:
  name: {{ include "vortex.fullname" . }}-controller
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "vortex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vortex.fullname" . }}-worker
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vortex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
