apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ryuo.fullname" . }}-config
  labels:
    {{- include "ryuo.labels" . | nindent 4 }}
data:
  RYUO_LOG_LEVEL: {{ .Values.logging.level | quote }}
  RYUO_LOG_FORMAT: {{ .Values.logging.format | quote }}
  RYUO_HTTP_PORT: {{ .Values.service.httpPort | quote }}
  RYUO_GRPC_PORT: {{ .Values.service.grpcPort | quote }}
